# Generated by Django 3.2.16 on 2023-04-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_value', models.IntegerField()),
                ('is_disabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('has_been_modified', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.module')),
            ],
        ),
    ]
