# Generated by Django 3.2.16 on 2023-04-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merchantapp_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bussiness_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usertype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
