# Generated by Django 4.1.3 on 2023-05-03 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_topup'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.accounttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.CharField(default='UGX', max_length=200),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_means',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='deposit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.deposit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='deposit_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_period',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.accounttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup',
            name='topup_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
