# Generated by Django 4.1.3 on 2023-05-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_deposit_account_type_deposit_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='deposit',
        ),
    ]
