# Generated by Django 4.1.3 on 2023-05-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_goal_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deposit',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='api.deposit'),
            preserve_default=False,
        ),
    ]
