# Generated by Django 4.1.3 on 2023-05-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_goal_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deposit'),
        ),
    ]
