# Generated by Django 4.1.3 on 2023-05-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_goal_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='deposit',
        ),
        migrations.AddField(
            model_name='deposit',
            name='goal',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='api.goal'),
            preserve_default=False,
        ),
    ]
