# Generated by Django 4.1.3 on 2023-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_nextofkin_email_alter_nextofkin_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='risk_analysis',
            field=models.CharField(default='Incomplete Risk profile', max_length=200, verbose_name='analysis'),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
