# Generated by Django 4.1.3 on 2023-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_riskprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='investment_option',
            field=models.CharField(default='Tbills', max_length=200, verbose_name='investment option'),
        ),
    ]
