# Generated by Django 4.1.3 on 2023-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_riskprofile_investment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='investment_option',
            field=models.CharField(default='risk_analysis', max_length=200),
        ),
    ]
