# Generated by Django 4.1.3 on 2023-07-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_withdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='withdarw_amount',
            new_name='withdraw_amount',
        ),
    ]
