# Generated by Django 4.1.3 on 2023-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_withdraw_goal_networth'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200)),
                ('bank_code', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction',
            field=models.CharField(default='', max_length=200),
        ),
    ]
