# Generated by Django 4.1.3 on 2023-07-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_withdraw_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankTransactions',
            new_name='BankTransaction',
        ),
    ]
