# Generated by Django 4.1.3 on 2023-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_banktransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
