# Generated by Django 4.1.3 on 2023-07-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_subscription_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='transaction',
        ),
        migrations.AddField(
            model_name='subscription',
            name='reference',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='reference_id',
            field=models.IntegerField(default=0),
        ),
    ]
