# Generated by Django 4.1.3 on 2023-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_subscription_amount_subscription_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='transaction',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='deposit',
            name='reference_id',
            field=models.IntegerField(default=0),
        ),
    ]
