# Generated by Django 4.1.3 on 2023-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_transaction_deposit_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='txRef',
            field=models.IntegerField(default=0),
        ),
    ]
