# Generated by Django 4.1.3 on 2023-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_subscription_txref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='txRef',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='txRef',
            field=models.CharField(max_length=200),
        ),
    ]
