# Generated by Django 4.1.3 on 2023-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_deposit_txref_alter_subscription_txref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='investment_option',
            field=models.CharField(default='Cash | Venture | Credit', max_length=200, verbose_name='investment option'),
        ),
    ]
