# Generated by Django 4.1.3 on 2023-07-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_goal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='status',
            new_name='is_active',
        ),
    ]
