# Generated by Django 3.2.16 on 2023-08-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_status_goal_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='static/photo.png', upload_to='static/profile/'),
        ),
    ]
