# Generated by Django 3.2.16 on 2023-08-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
