# Generated by Django 3.2.16 on 2023-11-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20230821_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='networth',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.banktransaction'),
        ),
    ]
