# Generated by Django 3.2.16 on 2023-11-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20231109_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='fundmanager', max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('company_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=0)),
                ('bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('banknumber', models.CharField(blank=True, max_length=255, null=True)),
                ('bankbranch', models.CharField(blank=True, max_length=255, null=True)),
                ('bankaccname', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(default='default_picture.jpg', upload_to='profile')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum', models.BigIntegerField(default=0)),
                ('interest', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=0)),
                ('unit', models.BigIntegerField(default=0)),
                ('fund', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('class_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investmentclass')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fundmanager')),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='available',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvestmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.BigIntegerField(default=0)),
                ('selling', models.BigIntegerField(default=0)),
                ('performance_value', models.IntegerField(default=0)),
                ('units', models.BigIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investmentoption')),
                ('fund_manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fundmanager')),
            ],
        ),
        migrations.CreateModel(
            name='FundWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdarw_amount', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fund_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fundmanager')),
            ],
        ),
    ]
