# Generated by Django 3.2.16 on 2023-11-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20231113_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investmentoption'),
        ),
    ]
