# Generated by Django 3.2.16 on 2023-11-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_remove_deposit_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='investment_option',
        ),
    ]
