# Generated by Django 3.2.16 on 2023-11-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20231113_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentoption',
            old_name='users_id',
            new_name='fund_manager',
        ),
        migrations.RenameField(
            model_name='investmentperformance',
            old_name='fund_manager_id',
            new_name='fund_manager',
        ),
    ]
