# Generated by Django 3.2.16 on 2023-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20231120_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskanalysis',
            old_name='score_range',
            new_name='score_max',
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='score_min',
            field=models.IntegerField(default=0),
        ),
    ]
