# Generated by Django 3.2.16 on 2023-11-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20231120_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='investment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investmentoption'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='units',
            field=models.BigIntegerField(default=0),
        ),
    ]
