# Generated by Django 3.2.16 on 2023-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20231123_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskanalysis',
            name='absolute_return',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='cash',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='venture',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='investment_option',
            field=models.CharField(default='Automatic Asset Allocation', max_length=200, verbose_name='investment option'),
        ),
    ]
