# Generated by Django 3.2.16 on 2023-11-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20231127_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmentoption',
            name='units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investmentperformance',
            name='units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='units',
            field=models.FloatField(default=0),
        ),
    ]
