# Generated by Django 3.2.16 on 2023-11-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20231128_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='networth',
            field=models.FloatField(default=0),
        ),
    ]
