# Generated by Django 3.2.16 on 2023-12-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_deposit_networth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundwithdraw',
            old_name='fund_manager_id',
            new_name='fund_manager',
        ),
    ]
