# Generated by Django 3.2.16 on 2023-12-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='networth',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_amount',
            field=models.FloatField(default=0),
        ),
    ]
