# Generated by Django 3.2.16 on 2023-12-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20231214_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='was_displayed',
            field=models.BooleanField(default=0),
        ),
    ]
