# Generated by Django 3.2.16 on 2023-12-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20231227_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentoption',
            old_name='user',
            new_name='fund_manager',
        ),
        migrations.RenameField(
            model_name='investmentperformance',
            old_name='user',
            new_name='fund_manager',
        ),
    ]
