# Generated by Django 3.2.16 on 2024-01-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20231227_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentoption',
            old_name='fund',
            new_name='description',
        ),
    ]
