# Generated by Django 3.2.16 on 2024-01-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_rename_fund_investmentoption_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='transaction',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='account_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='charge_amount',
            field=models.FloatField(default=0),
        ),
    ]
