# Generated by Django 3.2.16 on 2024-01-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20240102_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.banktransaction'),
        ),
    ]
