# Generated by Django 3.2.16 on 2024-01-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_withdraw_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='networth',
        ),
        migrations.RemoveField(
            model_name='networth',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='networth',
            name='user',
        ),
        migrations.AddField(
            model_name='networth',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deposit'),
        ),
    ]
