# Generated by Django 3.2.16 on 2024-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_networth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentclass',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
