# Generated by Django 3.2.16 on 2024-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_investmentclass_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentclass',
            name='logo',
            field=models.ImageField(default='default_picture.jpg', upload_to='investmentClasses'),
        ),
    ]
