# Generated by Django 3.2.16 on 2024-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_investmentclass_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_picture',
            field=models.ImageField(default='goal_picture.jpg', upload_to='goal'),
        ),
    ]
