# Generated by Django 3.2.16 on 2024-07-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_goal_goal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_picture',
            field=models.ImageField(default='default_picture.jpg', upload_to='goal'),
        ),
    ]
