# Generated by Django 3.2.16 on 2024-07-21 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0091_alter_goal_goal_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_means', models.CharField(max_length=200, null=True)),
                ('deposit_category', models.CharField(max_length=200, null=True)),
                ('deposit_amount', models.FloatField(default=0)),
                ('currency', models.CharField(default='UGX', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(default='', max_length=200)),
                ('reference_id', models.IntegerField(default=0)),
                ('txRef', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=0)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('units', models.FloatField(default=0)),
                ('opening_balance', models.FloatField(default=0)),
                ('interest', models.FloatField(default=0)),
                ('management_fee', models.FloatField(default=0)),
                ('closing_balance', models.FloatField(default=0)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.accounttype')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.goal')),
                ('investment_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investmentoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
