# Generated by Django 3.2.16 on 2024-08-30 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0092_newdeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_amount', models.FloatField(default=0)),
                ('deposit_amount', models.FloatField(default=0)),
                ('opening_balance', models.FloatField(default=0)),
                ('interest', models.FloatField(default=0)),
                ('management_fee', models.FloatField(default=0)),
                ('performance_fee', models.FloatField(default=0)),
                ('closing_balance', models.FloatField(default=0)),
                ('risk_profile', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('investment_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.investmentoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NewDeposit',
        ),
    ]
