# Generated by Django 3.2.16 on 2024-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20240830_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttrack',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
