# Generated by Django 3.2.16 on 2024-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_alter_investmenttrack_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentperformance',
            old_name='performance_value',
            new_name='management_fee',
        ),
        migrations.AddField(
            model_name='investmentperformance',
            name='performance_fee',
            field=models.IntegerField(default=0),
        ),
    ]
