# Generated by Django 3.2.16 on 2024-09-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20240902_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmenttrack',
            name='date_updated',
        ),
    ]
