# Generated by Django 3.2.16 on 2024-11-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_remove_investmenttrack_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttrack',
            name='out_performance',
            field=models.FloatField(default=0),
        ),
    ]
