# Generated by Django 3.2.16 on 2024-11-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_investmenttrack_out_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttrack',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
