# Generated by Django 3.2.16 on 2025-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_investmenttrack_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='txRef',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
