# Generated by Django 3.2.16 on 2025-01-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20250103_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttrack',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
