# Generated by Django 3.2.16 on 2025-01-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_investmenttrack_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('customer_reference', models.CharField(max_length=200, null=True)),
                ('internal_reference', models.CharField(max_length=200, null=True)),
                ('msisdn', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('provider', models.CharField(max_length=200, null=True)),
                ('charge', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
