# Generated by Django 3.2.16 on 2025-01-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
