# Generated by Django 3.2.16 on 2025-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
