# Generated by Django 3.2.16 on 2025-03-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_userprofile_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
