# Generated by Django 4.0.1 on 2025-04-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_group_groupgoal_media_message_groupinvitation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='receiver',
        ),
    ]
